apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- remedy-credentials-secret.yaml
- remedy-config-configmap.yaml
- remedy-adapter-deployment.yaml
- remedy-adapter-service.yaml
- remedy-apadter-route.yaml