apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: remedy-adapter
resources:
- ../../base
- remedy-adapter-namespace.yaml
images:
- name: PATCH_ME_SEE_OVERLAYS
  newName: quay.io/linuxeroagrio/remedy-adapter
  newTag: v1
patches:
- path: patch-remedy-config-configmap.yaml
  target:
    version: v1
    kind: ConfigMap
    name: remedy-config
- path: patch-remedy-credentials-secret.yaml
  target:
    version: v1
    kind: Secret
    name: remedy-credentials